TITLE RichDocter Builder - Dev Mode
ECHO OFF
ECHO Starting...
ECHO Compiling JavaScript...
call npm run build
Rem ECHO Compiling and executing golang build...
Rem call go build && RichDocter.exe
RichDocter.exe