TITLE Drafty Builder - Production Mode
ECHO OFF
ECHO Starting...
ECHO Compiling JavaScript...
call npm run build
ECHO Minifying JavaScript...
call npm run minify
ECHO Compiling and executing golang build...
call go build && drafty.exe