TITLE RichDocter Builder - Production Mode
ECHO OFF
ECHO Starting...
ECHO Running jest...
call npm run test
ECHO Compiling JavaScript...
call npm run build
ECHO Minifying JavaScript...
call npm run minify
ECHO Compiling golang linux binary...
call cmd /C "SET GOOS=linux&& SET GOARCH=amd64&& go build -o application"
ECHO Compiling and executing golang build...
call go build && RichDocter.exe