TITLE Drafty Builder - Production Mode
ECHO OFF
ECHO Starting...
ECHO Running pretest...
call npm run pretest
ECHO Running jest...
call npm run test
ECHO Compiling JavaScript...
call npm run build
ECHO Minifying JavaScript...
call npm run minify
ECHO Compiling and executing golang build...
call go build && drafty.exe