name: Build-And-Deploy
on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    name: Build Docker container
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag richdocter:$(date +%s)
        
