name: Push-to-EC2
on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build go backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./... -o /dist/RichDocter

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Deploy to ec2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
