name: Deploy to Amazon ECS

on:
  push:
    branches:
      - production
      - staging

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: richdocter

jobs:
  check_branch:
    name: Safeguard production branch
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'production' && github.head_ref != 'staging'
        run: |
          echo "ERROR: You can only merge to production from staging."
          exit 1
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Download Go modules
        run: go mod download

      - name: Run Go unit tests
        run: go test ./... -v
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    env:
      ECS_SERVICE: ${{ github.ref == 'refs/heads/production' && secrets.AWS_ECS_SERVICE || secrets.AWS_ECS_SERVICE_STAGING }}
      STRIPE_KEY: ${{ github.ref == 'refs/heads/production' && secrets.STRIPE_KEY || secrets.STRIPE_KEY_STAGING }}
      STRIPE_SECRET: ${{ github.ref == 'refs/heads/production' && secrets.STRIPE_SECRET || secrets.STRIPE_SECRET_STAGING }}
      MODE: ${{ github.ref_name }}
      run: |
          echo "app mode is set to ${{github.ref_name}}"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}" . \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_REGION=${{ env.AWS_REGION }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg AWS_MAX_RETRIES=${{ secrets.AWS_MAX_RETRIES }} \
            --build-arg AWS_BLOCKTABLE_MIN_WRITE_CAPACITY=${{ secrets.AWS_BLOCKTABLE_MIN_WRITE_CAPACITY }} \
            --build-arg GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }} \
            --build-arg GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }} \
            --build-arg GOOGLE_OAUTH_REDIRECT_URL=${{ secrets.GOOGLE_OAUTH_REDIRECT_URL }} \
            --build-arg AMAZON_OAUTH_CLIENT_ID=${{ secrets.AMAZON_OAUTH_CLIENT_ID }} \
            --build-arg AMAZON_OAUTH_CLIENT_SECRET=${{ secrets.AMAZON_OAUTH_CLIENT_SECRET }} \
            --build-arg AMAZON_OAUTH_REDIRECT_URL=${{ secrets.AMAZON_OAUTH_REDIRECT_URL }} \
            --build-arg MSN_OAUTH_CLIENT_ID=${{ secrets.MSN_OAUTH_CLIENT_ID }} \
            --build-arg MSN_OAUTH_CLIENT_SECRET=${{ secrets.MSN_OAUTH_CLIENT_SECRET }} \
            --build-arg MSN_OAUTH_REDIRECT_URL=${{ secrets.MSN_OAUTH_REDIRECT_URL }} \
            --build-arg ROOT_URL=${{ secrets.ROOT_URL }} \
            --build-arg SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            --build-arg VERSION=${{ github.sha }} \
            --build-arg STRIPE_SECRET=${{ env.STRIPE_SECRET }} \
            --build-arg STRIPE_KEY=${{ env.STRIPE_KEY }} \
            --build-arg VITE_STRIPE_KEY=${{ env.STRIPE_KEY }} \
            --build-arg VITE_MODE=${{ env.MODE }} \
            --build-arg MODE=${{ env.MODE }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          echo "WTF----------------------------------------------------------------------- $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}"
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}" > image.txt

      - name: Upload image artifact #have to store image as an artifact b/c github flags the output as a secret and skips it
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.txt

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      ECS_SERVICE: ${{ github.ref == 'refs/heads/production' && secrets.AWS_ECS_SERVICE || secrets.AWS_ECS_SERVICE_STAGING }}
      ECS_CLUSTER: ${{ github.ref == 'refs/heads/production' && secrets.AWS_ECS_CLUSTER || secrets.AWS_ECS_CLUSTER_STAGING }}
      ECS_TASK_DEFINITION: ${{ github.ref == 'refs/heads/production' && '.aws/aws_ecs_task.json' || '.aws/aws_ecs_task_staging.json' }}
      CONTAINER_NAME: ${{ github.ref == 'refs/heads/production' && 'richdocter' || 'web-container' }}
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image

      - name: Extract image name
        run: |
          echo "IMAGE=$(cat image.txt)" >> $GITHUB_ENV
          echo "RECEIVED---------------------------------------------- $(cat image.txt)"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: debug image env
        run: |
          echo "env image name: ${{env.IMAGE}}"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{env.IMAGE }}
        

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true