name: push-to-beanstalk
on: [push]
jobs:
    zip-files:
        steps:
            uses: actions/checkout@v2
            uses: papeloto/action-zip@v1
            with:
                files: dist/manifest.json
                dest: richdocter.zip
            uses: actions/upload-artifact@v1
                name: my-artifact
                path: ${{ github.workspace }}/result.zip

