name: push-to-beanstalk
on: [push]
jobs:
    zip-files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: papeloto/action-zip@v1
              with:
                files: public/css/, .ebextensions/, public/index.html, public/img/, public/robots.txt, public/favicon.ico, public/js/dist/bundle.min.js
                dest: richdocter.zip
            - uses: actions/upload-artifact@v1
              with:
                name: my-artifact
                path: ${{ github.workspace }}/richdocter.zip

