name: push-to-beanstalk
on:
    push:
        branches:
            - master

jobs:
    create-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jsdaniell/create-json@1.1.2
              id: config
              with:  
                name: "config.json"
                json: ${{ secrets.APP_CONFIG }}
            - uses: actions/upload-artifact@v1
              with:
                name: my-json
                path: ${{github.workspace}}/config.json

    beanstalk-zip:
        runs-on: ubuntu-latest
        needs: create-json
        steps:
            - uses: actions/checkout@v2
            - uses: actions/download-artifact@v2
              with:
                name: config.json
            - uses: montudor/action-zip@v1
              with:
                args: zip -qq -r richdocter.zip public .ebextensions Procfile application config.json
            - uses: actions/upload-artifact@v1
              with:
                name: richdocter.zip
                path: ${{ github.workspace }}/richdocter.zip
            
            

