name: push-to-beanstalk
on:
    push:
        branches:
            - master

jobs:
    create-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jsdaniell/create-json@1.1.2
              id: config
              with:  
                name: "config.json"
                json: ${{ secrets.APP_CONFIG }}
            - uses: actions/upload-artifact@v1
              with:
                name: my-json
                path: ${{github.workspace}}/config.json

    beanstalk-zip:
        runs-on: ubuntu-latest
        needs: create-json
        steps:
            - uses: papeloto/action-zip@v1
              with:
                files: public/ .ebextensions/ Procfile application ${{github.workspace}}/config.json
                recursive: true,
                dest: richdocter.zip
            - uses: actions/upload-artifact@v1
              with:
                name: my-artifact
                path: ${{ github.workspace }}/richdocter.zip
            
            

