name: push-to-beanstalk
on: [push]
jobs:
    zip-files:
        with:
            files: dist/manifest.json
            dest: richdocter.zip
        name: my-artifact
        path: ${{ github.workspace }}/result.zip
        steps:
            uses: actions/checkout@v2
            uses: papeloto/action-zip@v1
            uses: actions/upload-artifact@v1
            

